#!/bin/bash

if [ ! $# -eq 4 ]
then
    echo "Usage: $0 \"equation\" from to epsilon"
    exit
fi

echo "double f(const double x) { return ($1); }" > function.h

echo "Compiling ..."
g++ -std=c++17 bisect.cpp -o bisect.elf
if [ ! $? -eq 0 ]
then
    echo "Failed to compile."
    exit
fi

echo "Searching for roots of \"$1\" on interval ($2; $3) with percision $4:"
./bisect.elf "$2" "$3" "$4"
if [ ! $? -eq 0 ]
then
    echo "No roots found."
    exit
fi
