#!/bin/bash

if [ $# -lt 5 ]
then
    echo "Usage: $0 [bisect/parab] \"equation\" from to epsilon {plot.png}"
    exit
fi

if [ "$1" != "bisect" ] && [ "$1" != "parab" ]
then
    echo "Invalid method: $1"
    exit
fi

echo "double f(const double x) { return ($2); }" > function.h

echo "Compiling ..."
g++ -std=c++17 $1.cpp -o $1.elf
if [ ! $? -eq 0 ]
then
    echo "Failed to compile."
    exit
fi

PLOT_OUTPUT="$1.png"
if [ ! -z "$6" ]
then
    PLOT_OUTPUT="$6"
fi

echo "[$1] \"$2\" ($3; $4) ~ $5:"
./$1.elf "$3" "$4" "$5" | ./plot.R "$2" "$3" "$4" "$PLOT_OUTPUT"
if [ ! $? -eq 0 ]
then
    echo "No roots found."
    exit
fi

convert "$PLOT_OUTPUT" -trim "$PLOT_OUTPUT"

if [ -z "$6" ]
then
    (feh "$PLOT_OUTPUT" &)
fi

